[package]
name = "newsletter"
version = "0.2.0"
authors = ["person-m <melvin.personnier@gmail.com>"]

[dependencies]
diesel = { version = "1.0.0", features = ["mysql"] }
dotenv = "0.9.0"
rocket = "0.3.6"
rocket_codegen = "0.3.6"
