[package]
name = "website"
version = "0.1.0"
authors = ["Melvin PERSONNIER <melvin.personnier@gmail.com>"]

[dependencies]
diesel = { version = "1.0.0", features = ["mysql"] }
dotenv = "0.9.0"
rocket = "0.3.6"
rocket_codegen = "0.3.6"
lazy_static = "1.0"
r2d2-diesel = "1.0"
r2d2 = "0.8"
